=== zx21student301/Interfaz/HTML/XML/casoFinal03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="pedidos" >
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pedido" maxOccurs="unbounded" >
          <xs:complexType>
          <xs:sequence>
            <xs:choice>
              <xs:element name="cliente" >
                <xs:complexType>
                <xs:sequence>
                <xs:element name="MOTE" type="xs:string" />
                </xs:sequence>
                  <xs:attribute name="NIF" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="empresa" >
                <xs:complexType>
                  <xs:attribute name="CIF" use="required" >
                    <xs:simpleType>
                      <xs:restriction base="xs:int">
                        <xs:minInclusive value="0000"/>
                        <xs:maxInclusive value="9999"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              </xs:choice>
              <xs:element name="producto" type="xs:string" maxOccurs="unbounded" />
              <xs:element name="fecha" type="xs:string" />
              <xs:element name="factura" minOccurs="0" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="emisor" type="xs:string" maxOccurs="unbounded" />
                    <xs:element name="total" type="xs:int" maxOccurs="unbounded" />
                    <xs:element name="fechaFactura" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="numFactura" type="xs:string" use="required" />
                  <xs:attribute name="cliente_factura" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== zx21student301/Interfaz/HTML/XML/casoFinal03.xml
<?xml version="1.0" encoding="UTF-8"?>
  <pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="casoFinal03.xsd">
    <pedido>
      <empresa CIF="1000"/>
      <producto>Máquina de coser</producto>
      <fecha>23/08/2003</fecha>
      <factura numFactura="F1" cliente_factura="E45">
        <emisor>Empresa S.A</emisor>
        <total>2000</total>
        <fechaFactura>30/08/2003</fechaFactura>
      </factura>
    </pedido>
    <pedido>
      <cliente NIF="C1">
        <MOTE>Juan</MOTE>
      </cliente>
      <producto>Romba</producto>
      <fecha>10/01/2015</fecha>
      <factura numFactura="F2">
        <emisor>Empresa S.A</emisor>
        <total>1500</total>
        <fechaFactura>20/01/2015</fechaFactura>
      </factura>
    </pedido>
  </pedidos>
